#!/usr/bin/env python3
"""Decode logs generated by advanced_cpp example."""
import subprocess
import glob
import os

PRIVATE_KEY = "12a75cf111918579712b8158903c4b75ae5fb61355b85c2884ffaab5682a02c3"
LOGLND = os.path.join(os.path.dirname(__file__), "..", "build", "tools", "Release", "loglnd.exe")

for f in glob.glob("logs/*.blog") + glob.glob("logs/*.mmap"):
    subprocess.run([LOGLND, "-k", PRIVATE_KEY, f])
