#!/usr/bin/env python3
"""Decode logs generated by advanced_cpp example."""
import subprocess
import glob
import os

PRIVATE_KEY = "af3cd491a07442a660ac6ce5884ece8baa52e5437afa2ca7e9cb5589e0fe7e25"
LOGLND = os.path.join(os.path.dirname(__file__), "..", "build", "tools", "Release", "loglnd.exe")

for f in glob.glob("logs/*.blog") + glob.glob("logs/*.mmap"):
    subprocess.run([LOGLND, "-k", PRIVATE_KEY, f])
